// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRGUSJfSayb5yu-7boZxUxfzO9bR46_JQ',
    appId: '1:116183397616:web:b647227708a9047290be35',
    messagingSenderId: '116183397616',
    projectId: 'rebyu-c98f5',
    authDomain: 'rebyu-c98f5.firebaseapp.com',
    storageBucket: 'rebyu-c98f5.appspot.com',
    databaseURL: 'https://rebyu-c98f5-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Lp3tmg3i-0jYU4VTcPmMb7Y94JSuMFc',
    appId: '1:116183397616:android:a4270951ee26fe1490be35',
    messagingSenderId: '116183397616',
    projectId: 'rebyu-c98f5',
    storageBucket: 'rebyu-c98f5.appspot.com',
    databaseURL: 'https://rebyu-c98f5-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYj42nGbFgC-KggPfzSJeuObR4QKs2Bw',
    appId: '1:116183397616:ios:ea61968f568bd72990be35',
    messagingSenderId: '116183397616',
    projectId: 'rebyu-c98f5',
    storageBucket: 'rebyu-c98f5.appspot.com',
    iosBundleId: 'com.example.rebyu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZYj42nGbFgC-KggPfzSJeuObR4QKs2Bw',
    appId: '1:116183397616:ios:ea61968f568bd72990be35',
    messagingSenderId: '116183397616',
    projectId: 'rebyu-c98f5',
    storageBucket: 'rebyu-c98f5.appspot.com',
    iosBundleId: 'com.example.rebyu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRGUSJfSayb5yu-7boZxUxfzO9bR46_JQ',
    appId: '1:116183397616:web:22c427ed54eaa6fc90be35',
    messagingSenderId: '116183397616',
    projectId: 'rebyu-c98f5',
    authDomain: 'rebyu-c98f5.firebaseapp.com',
    storageBucket: 'rebyu-c98f5.appspot.com',
  );
}
